name: "web_app"
mode: "dev"
version: "v0"
port: 8081
start_time: "2025-11-26"
machine_id: 1
jwt_secret: "jimoruchen"
jwt_expire: 7
jwt_refresh_secret: "jimoruchen"
jwt_refresh_expire: 168
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 30
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "200088"
  db_name: "my_blog"
  max_open_conns: 200
  max_idle_conns: 100

gorm:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "200088"
  db_name: "my_blog"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

email:
  host: "smtp.qq.com"
  port: 465
  username: "1007896918@qq.com"      # 发件人邮箱
  password: "zhtyuvomganbbcei"  # SMTP 授权码（非登录密码！）
  from_name: "jimoruchen"